mantis_namn = [
    "Mantis Heat",
    "Mantis Rysk Atlantis",
    "Mantis Meat",
    "LennartLover JockeSör",
    "En grå get",
    "Mantis Mathilda",
    "Mantis X Max",
    "Mantis Gnuttan",
    "Mantis Mr.Alexanderman",
    "Mantis Hermacho",
    "Mantis Pippilongbong",
    "Filip Andersson",
    "Shablaaa",
    "Mantis FilieN",
    "Mantis Mejlvang",
    "Mantis Jyrgen von Becker",
    "Mantis Sert",
    "Adam Lundberg",
    "Mantis Knarkus",
    "Mantis Nibbasaurus",
    "Mantis nalle",
    "Mantis Victor Persson & Jacob persson",
    "Mantisarna i Stockholm",
    "Mantisen Gustav Lindqvist",
    "Mantisen Fredrik Grahn",
    "Mantisen Viktor Dalhström",
    "Mantisen Joel",
    "Mantisen William",
    "Mantisen Jonathan Hallstenson"
]